import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import Navbar from "@/component/navbar/page";
import Footer from "@/component/Footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader />
        <Navbar/>
        <Footer/>
      {children}</body>

    </html>
  );
}
